# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20645ec23f23566d08822739f5918e6583a51cae597f6c1c533bac1ff89b6009560baeb2c1dd5a4617b2b71aedba9c8942407b8e43ccaadbb362209d16029219

test:
  secret_key_base: 580ae2dc3d3037cbc9add0a9a6a8bdfc057911b7c3ff2eda9e0e0a5bd8110fb9feeeffff34bccb74c2c0b6620dcff5849903096b70cfcf118c33603476dff6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
